# Database Configuration
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    hikari:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: dust
      password: 1234

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #??? ??

#
---
spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:host.docker.internal:1521:XE
    username: dust
    password: 1234