# Database Configuration
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    hikari:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: dust
      password: 1234

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #??? ??

server:
  port: 8080